"""Planner agent built with Gemini and Pydantic AI."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator
from pydantic_ai import Agent

from ai.agents.gemini import GeminiSettings, build_google_model
from ai.prompts import PLANNER_SYSTEM_PROMPT, build_planner_user_prompt


class PlannedMeal(BaseModel):
    """Single meal candidate returned by the planner."""

    name: str = Field(min_length=1, description="Meal name.")
    meal_type: Literal["breakfast", "lunch", "dinner", "snack"] = Field(
        description="Meal slot for the plan.",
    )
    ingredient_names: list[str] = Field(
        default_factory=list,
        description="Ingredient names needed for this meal.",
    )
    estimated_cost_eur: float = Field(
        ge=0,
        description="Estimated meal cost in EUR.",
    )
    rationale: str = Field(
        min_length=1,
        description="Short reason for including this meal.",
    )


class PlannerOutput(BaseModel):
    """Structured plan proposal generated by the planner agent."""

    summary: str = Field(
        min_length=1, description="Short overview of the generated plan."
    )
    meals: list[PlannedMeal] = Field(
        default_factory=list,
        description="Meal candidates included in the plan.",
    )
    total_estimated_cost_eur: float = Field(
        ge=0,
        description="Estimated total plan cost in EUR.",
    )
    assumptions: list[str] = Field(
        default_factory=list,
        description="Assumptions made due to missing or ambiguous inputs.",
    )
    missing_information: list[str] = Field(
        default_factory=list,
        description="Data points needed to improve confidence in the plan.",
    )


class PlannerConstraints(BaseModel):
    """Constraint bundle used by the planner to shape meal generation."""

    budget_eur: float | None = Field(
        default=None,
        ge=0,
        description="Maximum total budget in EUR.",
    )
    days: int | None = Field(
        default=None,
        ge=1,
        le=14,
        description="Number of planning days.",
    )
    servings_per_meal: int | None = Field(
        default=None,
        ge=1,
        le=12,
        description="Target servings per meal.",
    )
    allergies: list[str] = Field(
        default_factory=list,
        description="Allergens that must be excluded.",
    )
    dislikes: list[str] = Field(
        default_factory=list,
        description="Ingredients or foods the user wants to avoid.",
    )
    cuisine_preferences: list[str] = Field(
        default_factory=list,
        description="Preferred cuisines to prioritize.",
    )


class PlannerRequest(BaseModel):
    """Input payload for the planner agent."""

    user_request: str = Field(
        min_length=1,
        description="Natural-language planning request from the user.",
    )
    constraints: PlannerConstraints = Field(
        default_factory=PlannerConstraints,
        description="Structured planning constraints extracted from user input.",
    )

    @model_validator(mode="before")
    @classmethod
    def _migrate_legacy_shape(cls, data: Any) -> Any:
        """Accept legacy flat request fields and map them into constraints."""

        if not isinstance(data, dict) or "constraints" in data:
            return data

        legacy_keys = {
            "budget_eur",
            "days",
            "servings_per_meal",
            "allergies",
            "dislikes",
            "cuisine_preferences",
        }
        constraints = {key: data[key] for key in legacy_keys if key in data}
        if not constraints:
            return data

        payload = {key: value for key, value in data.items() if key not in legacy_keys}
        payload["constraints"] = constraints
        return payload


@dataclass(slots=True)
class PlannerDependencies:
    """Runtime context passed into planner execution."""

    retrieved_context: dict[str, Any] = field(default_factory=dict)
    extra_instructions: list[str] = field(default_factory=list)


def create_planner_agent(
    *,
    model: Any | None = None,
    settings: GeminiSettings | None = None,
    api_key: str | None = None,
) -> Agent[PlannerDependencies, PlannerOutput]:
    """Create the planner agent with structured JSON output."""

    resolved_model = model or build_google_model(settings=settings, api_key=api_key)
    return Agent(
        resolved_model,
        deps_type=PlannerDependencies,
        output_type=PlannerOutput,
        system_prompt=PLANNER_SYSTEM_PROMPT,
    )


def build_planner_prompt(
    request: PlannerRequest,
    deps: PlannerDependencies | None = None,
) -> str:
    """Compose the planner user prompt from request + retrieval context."""

    dependencies = deps or PlannerDependencies()
    constraints = request.constraints.model_dump(exclude_none=True)
    retrieval_context = {
        "retrieved_context": dependencies.retrieved_context,
        "extra_instructions": dependencies.extra_instructions,
    }
    return build_planner_user_prompt(
        user_request=request.user_request,
        extracted_constraints=constraints,
        retrieval_context=retrieval_context,
    )


def run_planner(
    request: PlannerRequest,
    *,
    agent: Agent[PlannerDependencies, PlannerOutput],
    deps: PlannerDependencies | None = None,
) -> PlannerOutput:
    """Run planner synchronously and return a validated output object."""

    dependencies = deps or PlannerDependencies()
    prompt = build_planner_prompt(request, dependencies)
    return agent.run_sync(prompt, deps=dependencies).output
